#!/bin/bash

echo "🧹 清除浏览器缓存指南"
echo ""
echo "浏览器缓存了 localhost:3000 的重定向规则，导致访问其他项目时自动跳转到 /zh"
echo ""
echo "📋 解决方法（选择其中一种）："
echo ""
echo "方法1: 使用隐身模式（最快）"
echo "  Chrome/Edge: Cmd+Shift+N (Mac) 或 Ctrl+Shift+N (Win)"
echo "  Safari: Cmd+Shift+N"
echo "  Firefox: Cmd+Shift+P (Mac) 或 Ctrl+Shift+P (Win)"
echo ""
echo "方法2: 清除站点数据"
echo "  1. 打开开发者工具 (F12)"
echo "  2. Application → Storage"
echo "  3. 点击 'Clear site data'"
echo "  4. 勾选所有选项，点击 'Clear data'"
echo ""
echo "方法3: 清除浏览器缓存"
echo "  Chrome/Edge:"
echo "    1. Cmd+Shift+Delete (Mac) 或 Ctrl+Shift+Delete (Win)"
echo "    2. 选择 '所有时间'"
echo "    3. 勾选 '缓存的图片和文件'"
echo "    4. 点击 '清除数据'"
echo ""
echo "方法4: 硬刷新页面"
echo "  Chrome/Edge/Safari: Cmd+Shift+R (Mac) 或 Ctrl+Shift+R (Win)"
echo "  Firefox: Cmd+Shift+R (Mac) 或 Ctrl+F5 (Win)"
echo ""
echo "方法5: 禁用缓存（开发模式）"
echo "  1. F12 打开开发者工具"
echo "  2. Network 标签"
echo "  3. 勾选 'Disable cache'"
echo "  4. 保持开发者工具打开"
echo ""
echo "💡 推荐："
echo "  - 开发时使用隐身模式（最简单）"
echo "  - 或者在开发者工具中勾选 'Disable cache'"
echo ""
