#!/bin/bash

echo "🧹 清除 Chrome localhost:3000 重定向缓存"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤1: 在 Chrome 地址栏输入（复制粘贴）:"
echo ""
echo "chrome://net-internals/#dns"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤2: 点击 'Clear host cache' 按钮"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤3: 在地址栏输入（复制粘贴）:"
echo ""
echo "chrome://net-internals/#sockets"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤4: 点击 'Flush socket pools' 按钮"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤5: 清除所有缓存 (Cmd+Shift+Delete)"
echo ""
echo "  时间范围: 不限时间"
echo "  勾选: ☑ Cookie 及其他网站数据"
echo "        ☑ 缓存的图片和文件"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤6: 完全退出 Chrome (Cmd+Q)"
echo "       等待3秒后重新打开"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤7: 访问 http://localhost:3000"
echo "       应该不会再跳转到 /zh 了 ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 如果还是不行，试试终极方案:"
echo "   使用隐身模式 (Cmd+Shift+N)"
echo ""
