#!/usr/bin/env bash
# ============================================================================
# sync-themes.sh — DISPATCH-142 Phase B token sync
#
# Copies shared/styles/themes.master.css to all 4 Next.js sites with
# a "DO NOT EDIT" banner prepended. dino-kids-app uses Vite SPA + App.css,
# not part of token system.
#
# Usage:
#   ./tools/sync-themes.sh           # sync master → 4 sites
#   ./tools/sync-themes.sh --check   # exit 1 if any site drifts from master
#
# CI: .github/workflows/sync-themes.yml runs --check on PRs.
# ============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MASTER="$ROOT_DIR/shared/styles/themes.master.css"
HEADER="$ROOT_DIR/tools/themes-banner.txt"

# 4 target sites
TARGETS=(
  "$ROOT_DIR/wizPulseAI-com/src/styles/themes.css"
  "$ROOT_DIR/auth-wizpulseai-com/src/styles/themes.css"
  "$ROOT_DIR/db-wizPulseAI-com/src/styles/themes.css"
  "$ROOT_DIR/fashion-wizpulseai-com/src/styles/themes.css"
)

if [ ! -f "$MASTER" ]; then
  echo "❌ Master file not found: $MASTER"
  exit 1
fi

MODE="${1:---sync}"

# Create banner
cat > "$HEADER" <<'EOF'
/* 🚨 DO NOT EDIT 🚨
 * This file is auto-generated by tools/sync-themes.sh from
 * shared/styles/themes.master.css. Direct edits will be lost on next sync.
 * To change tokens: edit shared/styles/themes.master.css + re-run sync.
 */

EOF

if [ "$MODE" = "--check" ]; then
  DRIFT=0
  for target in "${TARGETS[@]}"; do
    if [ ! -f "$target" ]; then
      echo "⚠️  Missing: $target"
      DRIFT=1
      continue
    fi
    # Strip banner from target, compare with master
    expected=$(cat "$HEADER" "$MASTER")
    actual=$(cat "$target")
    if [ "$expected" != "$actual" ]; then
      echo "❌ Drift: $target"
      DRIFT=1
    else
      echo "✅ In sync: $(basename "$(dirname "$(dirname "$target")")")"
    fi
  done
  rm -f "$HEADER"
  if [ "$DRIFT" -eq 1 ]; then
    echo ""
    echo "Run ./tools/sync-themes.sh to re-sync."
    exit 1
  fi
  echo ""
  echo "All 4 sites in sync with master."
  exit 0
fi

# Sync mode (default)
echo "Syncing master → 4 sites..."
for target in "${TARGETS[@]}"; do
  target_dir="$(dirname "$target")"
  if [ ! -d "$target_dir" ]; then
    echo "⚠️  Skipping (dir not found): $target_dir"
    continue
  fi
  cat "$HEADER" "$MASTER" > "$target"
  site=$(basename "$(dirname "$target_dir")")
  echo "✅ $site/src/styles/themes.css"
done
rm -f "$HEADER"
echo ""
echo "Synced. Next: cd each repo + commit + push."
